# Generated by Django 5.2.8 on 2025-11-29 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ranges_price', models.CharField(choices=[('Economical-Level', 'اقتصادی'), ('Mid-Range', 'میان رده'), ('High-End', 'بالا رده')], default='Mid-Range', max_length=20)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('watch_genders', models.CharField(choices=[("Men's", 'مردانه'), ("Women's", 'زنانه'), ('Unisex', 'اسپورت')], default='Unisex', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0, help_text='به تومان')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('off', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_waterproof', models.BooleanField(default=False)),
                ('watch_type', models.CharField(choices=[('Quartz', 'کوارتز'), ('LCD', 'کامپیوتری'), ('Mechanical', 'مکانیکی'), ('Smart', 'هوشنمد')], default='Quartz', max_length=20)),
                ('watch_straps', models.CharField(choices=[('Buckle', 'سگکی'), ('Leather', 'چرمی'), ('Plastic', 'لاستیکی')], default='Buckle', max_length=20)),
                ('watch_shapes', models.CharField(choices=[('Round', 'گرد'), ('Square', 'مربع'), ('Rectangle', 'مستطیلی'), ('Oval', 'بیضی')], default='Round', max_length=20)),
                ('watch_materials', models.CharField(choices=[('Stainless Steel', 'استیل ضد زنگ'), ('Titanium', 'تیتانیوم'), ('Gold Plated', 'با آبکاری طلا'), ('Plastic', 'پلاستیک'), ('Ceramic', 'سرامیک')], default='Stainless Steel', max_length=20)),
                ('warranty', models.PositiveIntegerField(default=0, help_text='in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ['-created_at', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='GalleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='watch_images')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['created_at', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
